### ISSUE TITLE
Does guicier support auto configuration via package scanning?

### ISSUE THREAD

**Issue by liorhar** [HubSpot/dropwizard-guicier#42] opened 2018-09-13 14:15 UTC
In the previous hubspot/dropwizard-guice project there was the option to set auto config via package scanning. I couldn't find an example or a reference to such support in this replacement project.
Is it supported? if not, do you plan to support it?

**Comment by jhaber** [comment] 2018-09-13 14:33
This appears to be a duplicate of #41, I'll respond there to avoid multiple conversations about the same topic

**Closed by jhaber** 2018-09-13 14:33 UTC
