### ISSUE TITLE
Guice warning when running - You are attempting to use a deprecated API 

### ISSUE THREAD

**Issue by darrenhaken** [HubSpot/dropwizard-guicier#11] opened 2016-08-09 19:44 UTC
When I launch Dropwizard I get the following warnings:

**WARN  [2016-08-09 19:41:50,338] com.google.inject.servlet.InternalServletModule: You are attempting to use a deprecated API (specifically, attempting to @Inject ServletContext inside an eagerly created singleton. While we allow this for backwards compatibility, be warned that this MAY have unexpected behavior if you have more than one injector (with ServletModule) running in the same JVM. Please consult the Guice documentation at https://github.com/google/guice/wiki/Servlets for more information.**

Any idea what might be causing this?

I'm using Dropwizard 1.0.0

**Comment by jhaber** [comment] 2016-08-09 20:36
Thanks for reporting this issue! I was able to reproduce in a project that uses [HubSpot/jackson-jaxrs-propertyfiltering](https://github.com/HubSpot/jackson-jaxrs-propertyfiltering). It seems that the root cause is that we never register the `GuiceServletContextListener`. I added what seems like the most straight-forward fix in ca22b7bfaf0307129f3e60c5bab471ad741a186e and the warning is gone from my example application. Can you try building with that commit? If it works for you as well I'll cut a release

**Comment by jhaber** [comment] 2016-09-23 22:24
Released as part of 1.0.0.4

**Closed by jhaber** 2016-09-23 22:24 UTC
